server:
  port: 8083

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    spring:
    datasource:
    initialization-mode=always:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/myoauth2
    username: elhanz
    password: elhanz
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/elhanz
          jwk-set-uri: http://localhost:8180/realms/elhanz/protocol/openid-connect/certs

